cluster.name: "mozilla-cluster"
network.host: 0.0.0.0
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true

# Configuration mémoire
bootstrap.memory_lock: true

# Configuration disque
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 1gb
cluster.routing.allocation.disk.watermark.high: 500mb
cluster.routing.allocation.disk.watermark.flood_stage: 100mb

# Désactiver la vérification SSL pour le développement
xpack.security.http.ssl:
  enabled: false
xpack.security.transport.ssl:
  enabled: false